### ISSUE TITLE
Nhiều expectedOutputtrong testcase ?

### ISSUE THREAD

**Issue by lamlam-l** [HANU-GDSC/hanuoj-be#9]
Đôi khi 1 input có thể cho ra nhiều output khác nhau, như bài two sum trên leetcode chẳng hạn đáp án là 2 số tự nhiên không quan trọng vị trí

**Comment by Wohoo22** [comment]
Những bài như này thường có cả code của tác giả để check tính đúng đắn của output, bởi vì những bài tương tự mà phức tạp hơn thì tổ hợp output đúng của nó rất nhiều, ko thể sinh hết expected output được mà phải check = code. Tính năng này sẽ có trong tương lai, giờ tạm thời chưa có, đề bài phải yêu cầu coder sinh output theo 1 thứ tự nào đấy (ví dụ từ bé đến lớn)
